export default Object.freeze({
  LAYERSPERMISSIONS:"LayersPermissions",
  EMPLOYEEPERMISSIONS:"EmployeePermissions",
  ALLTALABTS:"AllTalabats",
  NEWTABLETUSER:"NewTabletUser",
  NEWTABLETAPP:"NewTabletApp",
  TALABTS:"Talabats",
  WATERSERVICES:"WaterServices",
  ELECTRICSERVICES:"ElectricServices",
  WATERREADERSERVICES:"WaterReaderServices",
  UPDATEWATERSERVICE:"UpdateWaterService",
  BUILDINGUNITS:"BuildingUnit",
  OVERTIMEREG:"OverTimeReg",
  PROJECTSMAP:"ProjectsMap",
  PROJECTSPUBLICMAP:"ProjectsPublicMap",
  CARCOUNT:"CarCount",
  CONTAINER:"Container",
  STREETSIGN:"StreetSign",
  FARM:"Farm",
  BLACKLIST:"BlackList",
  ADDLANDMARK:"AddLandmark",
  ADDPUMP:"AddBump",
  OVERTIME:"OverTime",
  TRACKING:"Tracking",
  SEARCHCUST:"SearchCust",
  SEARCHEMP:"SearchEmp",
  PRINT:"Print",
  UPDATECUST :"UpdateCust",
  WATERTANK:"WaterTank",
  EMPLEAVES:"EmpLeaves",
  SIGNBOARD :"SignBoard",
  TAKEIMAGE:"TakeImage",
  UNITWARNING:"UnitWarn",
  BUILDINGSPROC:"BuildingsProces",
  TAXTOTAL :"TaxTotal",
  TAXDETAILS :"TaxDetails",
  TABLET:"Tablet",
  TABLETMAIN:"TabletMain",
  EPAYMENT:"EPayment",
  TAXAGENT:"TAXAGENT",
  WATERCONSUM:"WaterConsum",
  TABLETADMIN:"TabletAdmin",
  TABLETUPLOAD:"TabletUpload",
  TABLETDOWNLOAD:"TabletDownload",
  TABLETONLINE:"TabletOnline",
  ALLMAILS :"AllMails",
  ABOUTAPP:"AboutApp",
  DOCS:"Docs",
  MAILS:"Mails",
  PERMISSIONSTRANS:"PermissionsTrans",
  PERMISSIONS:"Permissions",
  WATERADMIN:"WaterAdmin",
  NOTIFICATIONADMIN:"NotificationAdmin",
  SALARY:"Salary",
  MYINFO:"MyInfo",
  LOGINHM:"Loginhm",
  USERTAX:"UserTax",
  COMPLAINTS:"Complaints",
  PLACES:"Places",
  REQUESTS:"Requests",
  UNITS:"Units",
  WATERSCHEDULE:"WaterSchedule",
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LISTINGS: "Listings",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  FEED: "Feed",
  ACCOUNT: "Account",
  HOME: "Home",
  SEARCH: "Search",
  PAYMENT:"Paymeny",
  ARSARAYICBEDELSORGULAMA: "ArsaRayicBedelSorgulama",
  ARSARAYICBEDELDETAY: "ArsaRayicBedelDetay",
  ANONIMBORCSORGULAMA: "AnonimBorcSorgulama",
  ANONIMBORCDETAY: "AnonimBorcDetay",
  BARKODLUBELGESORGULAMA: "BarkodluBelgeSorgulama",
  BARKODLUBELGEDETAY: "BarkodluBelgeDetay",
  COPTOPLAMABILGISISORGULAMA: "CopToplamaBilgisiSorgulama",
  COPTOPLAMABILGISIDETAY: "CopToplamaBilgisiDetay",
  ENCUMENGUNDEMDETAY: "EncumenGundemDetay",
  ENCUMENKARARSORGULAMA: "EncumenKararSorgulama",
  ENCUMENKARARDETAY: "EncumenKararDetay",
  ENCUMENKARARDETAYACIK: "EncumenKararDetayAcik",
  IHALEDETAY: "IhaleDetay",
  IHALEDETAYACIK: "IhaleDetayAcik",
  IMARDURUMSORGULAMA: "ImarDurumSorgulama",
  IMARDURUMDETAY: "ImarDurumDetay",
  MECLISGUNDEMDETAY: "MeclisGundemDetay",
  MECLISKARARSORGULAMA: "MeclisKararSorgulama",
  MECLISKARARDETAY: "MeclisKararDetay",
  NIKAHSALONSORGULAMA: "NikahSalonSorgulama",
  NIKAHSALONDETAY: "NikahSalonDetay",
  NOBETCIECZANESORGULAMA: "NobetciEczaneSorgulama",
  NOBETCIECZANEDETAY: "NobetciEczaneDetay",
  FAALIYETPLANIDETAY: "FaaliyetPlaniDetay",
  HIZMETSORGULAMA: "HizmetSorgulama",
  HIZMETDETAY: "HizmetDetay",
  ASKIDAKIIMARPLANILISTE: "AskidakiImarPlaniSorgulama",
  ASKIDAKIIMARPLANIDETAY: "AskidakiImarPlaniDetay",
  BORCOZETDETAY: "BorcOzetDetay",
  TALEPBASVURU: "TalepBasvuru",
  TALEPBASVURUSORGULAMA: "TalepBasvuruSorgulama",
  TALEPBASVURUSORGULAMADETAY: "TalepBasvuruSorgulamaDetay",
  BEYANTASINMAZLARLISTE: "BeyanTasinmazlarListe",
  BEYANLARLISTE: "BeyanlarListe",
  BEYANDETAY: "BeyanDetay",
  BILDIRIMLERLISTE: "BildirimlerListe",
  BILDIRIMDETAY: "BildirimDetay",
  BILDIRIMARSABASVURUSCREEN: "BildirimArsaBasvuru",
  BILDIRIMBINABASVURUSCREEN: "BildirimBinaBasvuru",
  BILDIRIMCEVREBASVURUSCREEN: "BildirimCevreBasvuru",
  BILDIRIMILANBASVURUSCREEN: "BildirimIlanBasvuru",
  MAKBUZSORGULAMA: "MakbuzSorgulama",
  MAKBUZDETAY: "MakbuzDetay",
  TAHSILATSORGULAMA: "TahsilatSorgulama",
  TAHSILATLISTE: "TahsilatListe",
  TAHSILATDETAY: "TahsilatDetay",
  EVRAKSORGULAMA: "EvrakSorgulama",
  EVRAKDETAY: "EvrakDetay",
  ETKINLIKLERSCREEN: "Etkinlikler",
  HABERLERSCREEN: "Haberler",
  POSTAL: "Postal",
  MAPLOCSCREEN: "MapLoc",
  PROJELERSCREEN: "Projeler",
  BASKANYARDIMCILARISCREEN: "BaskanYardimcilari",
  MUDURLERSCREEN: "Mudurler",
  BASKANSCREEN: "Baskan",
  FAVORITES: "Favorites",
  TOPLANMALANLARILISTE: "ToplanmaAlanlari",
  NOTIFICATIONS: "Notifications",
  COUNCIL:"Council",
  COUNCIL1:"Council1",
  FOLLOWCOMP:"FollowComp",
  FOLLOWTRANSPORT:"FollowTransport",

  UPDATEINFO:"UpdateInfo",
  FOLLOWREQUEST:"FollowRequest",
  USERAPPOINTMENS:"UserAppointments",
  SERVICEINFO:"ServiceInfo"
    
});
